*** empty log message ***

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,4 +1,5 @@
 dnl Process this file with autoconf to produce a configure script.
+
 AC_INIT(cgi/index.c)
 
 AC_CANONICAL_SYSTEM
@@ -7,7 +8,7 @@ AM_INIT_AUTOMAKE(monolith, 1.0)
 AM_CONFIG_HEADER(include/config.h)
 AC_PREFIX_DEFAULT(/usr/bbs)
 
-AC_ARG_WITH(mysql, [  --with-mysql=DIR        use mysql database system  [default=yes]
+AC_ARG_WITH(mysql, [  --with-mysql[=DIR]      use mysql database system  [default=yes]
                           (requires mysql to be installed)],,with_mysql=yes)
 AC_ARG_WITH(rating, [  --with-rating           use message rating system  [default=yes]
                           (allows users to rate messages)],,with_rating=yes)
@@ -94,8 +95,8 @@ if test "x$grep_path" != "xno" ; then
 fi
 
 dnl Do a bit of mysql checking.
-echo "checking MySQL installation..."
 if test ! x${withval} = x && test -d "${withval}" && test -d "${withval}/include"; then
+    echo "checking MySQL installation in ${withval}..."
     mysql_dir=${withval}
     echo -n "  -> headers..."
     if test -d "${withval}/include"; then
@@ -119,31 +120,48 @@ if test ! x${withval} = x && test -d "${withval}" && test -d "${withval}/include
         echo " uh-oh"
     fi
     if test -f "${withval}/include/mysql.h"; then
-      AC_DEFINE(HAVE_MYSQL_H)
-      AC_DEFINE(USE_MYSQL)
-      AC_SUBST(MYSQL_INCLUDE)
-      AC_SUBST(MYSQL_LIB)
-      AC_SUBST(MYSQL_BIN)
+        AC_DEFINE(HAVE_MYSQL_H)
+        AC_DEFINE(USE_MYSQL)
+        AC_SUBST(MYSQL_INCLUDE)
+        AC_SUBST(MYSQL_LIB)
+        AC_SUBST(MYSQL_BIN)
+        mysql_app=${MYSQL_BIN}/mysql
     else
-      echo
-      echo "ARGH: Unable to locate mysql! Take cover! Self destructing in 3 seconds!"
-      echo
-      echo "Please install the MySQL database system, which is available for free from"
-      echo "http://www.mysql.org/ and run this program again. If you do have MySQL in-"
-      echo "stalled, check directory and file permissions, or create symbolic links so"
-      echo "configure can find it."
-      echo
-      exit 0
+        echo
+        echo "ARGH: Unable to locate mysql! Take cover! Self destructing in 3 seconds!"
+        echo
+        echo "Please install the MySQL database system, which is available for free from"
+        echo "http://www.mysql.org/ and run this program again. If you do have MySQL in-"
+        echo "stalled, use the option --with-mysql=DIR so that $0 can find it."
+        echo
+        exit 1
     fi
 else
-    echo
-    echo "ARGH: Unable to locate mysql! Take cover! Self destructing in 3 seconds!"
-    echo
-    echo "Please install the MySQL database system, which is available for free from"
-    echo "http://www.mysql.org/ and run this program again. If you do have MySQL in-"
-    echo "stalled, use the option --with-mysql=DIR so that $0 can find it."
-    echo
-    exit 0
+    dnl Look for global mysql installation.
+    dnl
+    AC_CHECK_HEADERS(mysql.h)
+    if test "x$ac_cv_header_mysql_h" = "xno" ; then
+        AC_CHECK_HEADERS(mysql/mysql.h)
+        if test "x$ac_cv_header_mysql_mysql_h" = "xno" ; then
+            echo
+            echo "ARGH: Unable to locate mysql! Take cover! Self destructing in 3 seconds!"
+            echo
+            echo "Please install the MySQL database system, which is available for free from"
+            echo "http://www.mysql.org/ and run this program again. If you do have MySQL in-"
+            echo "stalled, use the option --with-mysql=DIR so that $0 can find it."
+            echo
+            exit 1
+        else
+            AC_DEFINE(HAVE_MYSQL_MYSQL_H)
+            AC_CHECK_LIB(mysqlclient, mysql_connect)
+            AC_DEFINE(USE_MYSQL)
+        fi
+    else
+        AC_DEFINE(HAVE_MYSQL_H)
+        AC_CHECK_LIB(mysqlclient, mysql_connect)
+        AC_DEFINE(USE_MYSQL)
+    fi
+    mysql_app=mysql
 fi
 
 dnl Use message rating system?
@@ -209,7 +227,7 @@ if test "$no_create" != "yes" ; then
 
   dnl Update or create version stamp, but only if it' not
   dnl automagically running.
-  /bin/sh ./mkversion-sh $mysql_dir
+  /bin/sh ./mkversion-sh $mysql_app
 
   dnl Linux newbie stuff.
   dnl
@@ -252,3 +270,4 @@ if test "$no_create" != "yes" ; then
   echo "----------------------------------------------------------------------"
   echo
 fi
+
